name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        ports:
          - 9200:9200
        options: -e "discovery.type=single-node"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn httpx elasticsearch docker

          - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build and push Docker images
        run: |
            docker-compose up --build -d
            docker-compose push

      - name: Run tests
        run: |
          # Ajoutez ici les commandes pour exécuter vos tests
          echo "Running tests..."

      - name: Build and push Docker images
        run: |
          docker-compose up --build -d
          # Ajoutez ici les commandes pour pousser vos images Docker vers un registre

      - name: Deploy
        run: |
          echo "Deploying application..."
          # Ajoutez ici les commandes pour déployer votre application
