name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl -f http://localhost:9200 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn httpx elasticsearch docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          cd hands_on_microservices
          # Construire toutes les images définies dans le docker-compose mis à jour
          docker-compose build
          # Pousser les images sur Docker Hub (assure-toi que les images ont bien une balise pour le push)
          docker-compose push

      - name: Run tests
        run: |
          echo "Running tests..."
          # Ajoute ici tes commandes pour exécuter les tests unitaires ou d'intégration

      - name: Deploy
        run: |
          echo "Deploying application..."
          # Ajoute ici les commandes pour déployer ton application (par exemple, sur un cluster, un serveur, etc.)
